### ISSUE TITLE
Install Docker

### ISSUE THREAD

**Issue by jpoon** [Azure/service-fabric-linux-vagrant-onebox#4]
Was expecting the OneBox to mimic the same setup as a cluster deployed through Azure (ie. with Docker pre-installed). 

On that note, where does one find fabric logs of why things are unhealthy? I would generally turn to Event Viewer when on Windows but on the Linux cluster, I couldn't find any logs indicating why my container was not being deployed; searched through `journalctl -u servicefabric.servic`,  /home/sfuser/sfdevcluster and /lttng-traces and couldn't find anything with like "docker not installed"/"missing docker".

**Comment by mani-ramaswamy** [comment]
The apt repo doesn't always have the latest docker bits, and we want to rely only on deb dependencies. If you were to uninstall service fabric followed by a apt-get -f remove, we will remove all deps that SF brought in and so we can leave it in the pristine state (assuming no other sw was also using those dependencies -in which case apt will keep them).  However, if we installed docker by default on your one-box, since we need the latest bits, we'll have to bypass apt, and then during uninstall, we won't be able to know whether you are still using it or not....

Hence we ask you to install in your one-box directly from docker. In Azure, since we create the image and we don't expect you to uninstall SF bits, that wasn't a concern and we install docker.

**Comment by jpoon** [comment]
> In Azure, since we create the image and we don't expect you to uninstall SF bits, that wasn't a concern and we install docker.

Is this a valid scenario? Given it's a OneBox specifically built for ServiceFabric, I can't see a reason why I would ever want to uninstall Service Fabric from this VM.

> The apt repo doesn't always have the latest docker bits

I'm not entirely convinced that you _always_ want the latest Docker bits. Up until a couple weeks ago, Azure Container Service would use the _latest_ Docker version. Unfortunately, Docker 1.13.0 broke Kubernetes networking and effectively broke all new/existing clusters that were deployed using ACS. 

In any case, what I'm trying to achieve is local development/deployment before I push my bits to Azure. It'd be great if this OneBox mirrored that of one in Azure (is Docker pre-installed the only difference?); otherwise, documentation in the README outlining the differences would be beneficial.

**Comment by mani-ramaswamy** [comment]
Are you suggesting that the vagrant VM  doesn't have it? If that's the case, we'll fix it. However, if you are installing on a linux vm yourself, then you might be using it for other reasons as well.   We did have issues in the past where the latest bits from docker.io had some features that weren't in apt...

**Comment by jpoon** [comment]
That is correct, the vagrant VM defined in this repo does not have Docker preinstalled. I've added a docker install in my fork (https://github.com/jpoon/service-fabric-linux-vagrant-onebox/blob/master/Vagrantfile#L10), and can submit a PR, but it sounds like there is preference to bake it in the box itself.

**Comment by mani-ramaswamy** [comment]
We'll fix that with the next release (*have the Vagrant VM contain docker*). Meanwhile, the traces are @ /home/sfuser/sfdevcluster/data/log/work/WFab/0/0/Log/Fabric/

**Comment by jpoon** [comment]
Closed by https://github.com/Azure/service-fabric-linux-vagrant-onebox/commit/076e7a84f88f874b6e137a035ff8702a40633fc1. Looks like Docker is now included! Thanks.

**Comment by snapnurse-joshuamatthews** [comment]
@mani-ramaswamy how do I log in to the box to see these logs? Can't seem to find the ssh password anywhere

**Comment by jpoon** [comment]
`vagrant ssh`

**Comment by mani-ramaswamy** [comment]
That's right (what Jason said) - you don't need a password (unless you set one in the vagrantfile yourself).

**Comment by snapnurse-joshuamatthews** [comment]
Thanks! Exactly what I needed.
